# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29423b303d324a8a9e910755d0c630a2a2677a4540f00abd8120977da3a2b156b1ec23652b239354a06354533f757bf7487688585e5052a9ce42c9769775564c

test:
  secret_key_base: cb05a58c59d73ff55d4cc14933969d61c410910e174431e19454477aef6c3054cbd12688102a25c6e51c27ff80dc80f74b0dd95269f4333cd775b1e4803a1cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
